server:
  port: ${PORT:8080}
  address: ${HOST:0.0.0.0}

app:
  api:
    prefix: api

spring:
  application:
    name: subscription
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:subscriptiondb}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  jpa:
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.H2Dialect}
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  h2:
    console:
      enabled: true
      path: /h2-console
